# Generated by Django 4.2 on 2026-03-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmemory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat Memory', 'verbose_name_plural': 'Chat Memories'},
        ),
    ]
