# Generated by Django 4.2 on 2026-01-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='title',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
