# Generated by Django 4.2 on 2026-03-12 21:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gamemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
