# Generated by Django 4.2 on 2026-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_gamemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
