# Generated by Django 4.2 on 2026-01-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_gamecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='comment_pics/'),
        ),
    ]
